function export_to_google_sheets(metadata)
    % Google Form Response URL (Make sure it ends with /formResponse)
    googleFormURL = 'https://docs.google.com/forms/d/e/1FAIpQLSfBEOicBe2J1zBJ7mVMdDU-rou8O1z03t7UaPLA8KWeqNJRqw/formResponse';
    % Use weboptions to set character encoding
    options = weboptions('MediaType', 'application/x-www-form-urlencoded', 'Timeout', 30);
    % Submit data using name-value pairs instead of struct
    webwrite(googleFormURL, ...
        'entry.519407752', metadata.Date, ...
        'entry.1683411164', metadata.Time, ...
        'entry.1440913363', metadata.Strain, ...
        'entry.494790073', metadata.Age, ...
        'entry.1078593523', metadata.Frame, ...
        'entry.1431223806', metadata.Side, ...
        'entry.1893171480', metadata.NotesStart, ...
        'entry.50100112', metadata.NotesEnd, ...
        options); % Include options for correct encoding
    disp('Data successfully exported to Google Sheets.');
end
