function selections = get_input_parameters()
    % Create a figure window for the input dialog
    fig = uifigure('Name', 'Fly Experiment Setup', 'Position', [500 500 300 300]);  % Increased height
    % Dropdown for Strain
    uilabel(fig, 'Position', [20 240 80 22], 'Text', 'Fly Strain:');
    strainDropdown = uidropdown(fig, ...
        'Position', [120 240 150 22], ...
        'Items', {'csw1118', 'test'}, ...
        'Value', 'csw1118');
    % Dropdown for Age
    uilabel(fig, 'Position', [20 190 80 22], 'Text', 'Age of Fly:');
    ageDropdown = uidropdown(fig, ...
        'Position', [120 190 150 22], ...
        'Items', {'1', '2', '3', '4', '5', '6', '7', '8', 'NaN'}, ...
        'Value', '1');
    % Dropdown for Sex
    uilabel(fig, 'Position', [20 140 80 22], 'Text', 'Sex of Fly:');
    sexDropdown = uidropdown(fig, ...
        'Position', [120 140 150 22], ...
        'Items', {'Male', 'Female', 'NaN'}, ...
        'Value', 'Male');
    % Dropdown for Light Cycle
    uilabel(fig, 'Position', [20 90 80 22], 'Text', 'Light Cycle:');
    lightCycleDropdown = uidropdown(fig, ...
        'Position', [120 90 150 22], ...
        'Items', {'20:00_12:00', '01:00_17:00', 'NaN'}, ...
        'Value', '20:00_12:00');
    % Text field for Fly Name
    uilabel(fig, 'Position', [20 40 80 22], 'Text', 'Fly Name:');
    flyNameField = uieditfield(fig, 'text', ...
        'Position', [120 40 150 22], ...
        'Value', '');  % Empty default value
    % Variable to hold selections
    selections = struct('Strain', '', 'Age', '', 'Sex', '', 'LightCycle', '', 'FlyName', '');
    % Confirm Button with callback function to retrieve values and close the figure
    confirmButton = uibutton(fig, 'push', ...
        'Position', [100 10 100 30], ...
        'Text', 'Confirm', ...
        'ButtonPushedFcn', @(btn, event) confirmSelections());
    % Wait for the figure to close before proceeding
    uiwait(fig);

    % Callback function to store selections and close the figure
    function confirmSelections()
        selections.Strain = strainDropdown.Value;
        selections.Age = ageDropdown.Value;
        selections.Sex = sexDropdown.Value;
        selections.LightCycle = lightCycleDropdown.Value;
        selections.FlyName = flyNameField.Value;
        close(fig);
    end
end
